// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiPD4yX751PKcj60y7It4ncPAXzZ7-53E',
    appId: '1:395523073627:web:afc447c8e62f98dcb1c17e',
    messagingSenderId: '395523073627',
    projectId: 'flutter-todo-app-3eaf8',
    authDomain: 'flutter-todo-app-3eaf8.firebaseapp.com',
    storageBucket: 'flutter-todo-app-3eaf8.appspot.com',
    measurementId: 'G-H4L5F89PGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEwloW1dYJGrIcks_vbxJwhbVXnMSkoFs',
    appId: '1:395523073627:android:87e5b6570473638cb1c17e',
    messagingSenderId: '395523073627',
    projectId: 'flutter-todo-app-3eaf8',
    storageBucket: 'flutter-todo-app-3eaf8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPdzl-l2b8xds0qkX8r4PKFjXAjL2xiyw',
    appId: '1:395523073627:ios:1f6c811e34d959fdb1c17e',
    messagingSenderId: '395523073627',
    projectId: 'flutter-todo-app-3eaf8',
    storageBucket: 'flutter-todo-app-3eaf8.appspot.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPdzl-l2b8xds0qkX8r4PKFjXAjL2xiyw',
    appId: '1:395523073627:ios:05c8e5b32e781c93b1c17e',
    messagingSenderId: '395523073627',
    projectId: 'flutter-todo-app-3eaf8',
    storageBucket: 'flutter-todo-app-3eaf8.appspot.com',
    iosBundleId: 'com.example.todoapp.RunnerTests',
  );
}
